service: springboot-lambda

provider:
  name: aws
  runtime: java8
  memorySize: 1536
  timeout: 60

package:
  artifact: build/distributions/springboot-lambda.zip

#plugins:
#  - serverless-plugin-localstack
#
#custom:
#  localstack:
#    host: http://localhost
#    endpoints:
#      S3: http://localhost:4572
#      DynamoDB: http://localhost:4570
#      CloudFormation: http://localhost:4581
#      Elasticsearch: http://localhost:4571
#      ES: http://localhost:4578
#      SNS: http://localhost:4575
#      SQS: http://localhost:4576
#      Lambda: http://localhost:4574
#      Kinesis: http://localhost:4568

functions:
  users:
    handler: com.serverless.LambdaHandler
    events:
      - http:
          path: users
          method: get
          cors: true
      - http:
          path: users/{lastName}
          method: get
          cors: true
      - http:
          path: users/create
          method: post
          cors: true
           
